# Generated by Django 3.2.12 on 2022-04-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaylists', '0002_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='myplaylists.Song'),
        ),
    ]
